# Generated by Django 5.2.9 on 2026-01-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HubApp', '0003_rename_discription_products_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='image',
        ),
        migrations.AddField(
            model_name='products',
            name='images',
            field=models.ImageField(default=1, upload_to='product_image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_name',
            field=models.CharField(max_length=50),
        ),
    ]
