# Generated by Django 5.2.9 on 2026-01-22 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HubApp', '0004_remove_products_image_products_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='images',
            field=models.ImageField(upload_to='product_images'),
        ),
    ]
