# Generated by Django 5.2.9 on 2026-02-02 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HubApp', '0006_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='order',
            new_name='orders',
        ),
    ]
