# Generated by Django 5.2.9 on 2026-02-03 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HubApp', '0007_rename_order_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HubApp.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HubApp.users')),
            ],
        ),
    ]
