# Generated by Django 5.2.9 on 2026-02-04 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HubApp', '0008_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product',
            new_name='products',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='quantity',
            new_name='quantitys',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='users',
        ),
    ]
