# Generated by Django 5.2.9 on 2026-02-04 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HubApp', '0010_rename_products_cart_product_rename_users_cart_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='coustomer',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='product',
            new_name='items',
        ),
    ]
