# Generated by Django 5.2.9 on 2026-02-04 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HubApp', '0011_rename_user_cart_coustomer_rename_product_cart_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='items',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='quantitys',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='coustomer',
            new_name='user',
        ),
    ]
