# Generated by Django 5.2.9 on 2026-02-04 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HubApp', '0012_rename_items_cart_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product',
            new_name='products',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='users',
        ),
    ]
