# Generated by Django 5.2.9 on 2026-02-04 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HubApp', '0013_rename_product_cart_products_rename_user_cart_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='products',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='users',
            new_name='user',
        ),
    ]
