# Generated by Django 5.2.9 on 2026-02-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HubApp', '0014_rename_products_cart_product_rename_users_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_id',
            field=models.CharField(null=True),
        ),
    ]
