# Generated by Django 5.2.9 on 2026-03-25 12:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HubApp', '0015_products_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(4, 'erngi po myre')]),
        ),
    ]
