# Generated by Django 5.2.9 on 2026-03-25 12:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HubApp', '0016_alter_users_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(validators=[django.core.validators.MinLengthValidator(4, 'erngi po myre')]),
        ),
    ]
