# Generated by Django 5.2.9 on 2026-03-25 13:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HubApp', '0017_alter_users_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(4, 'Name must be at least 4 characters'), django.core.validators.RegexValidator(message='Name should contain only letters', regex='^[a-zA-Z ]+$')]),
        ),
        migrations.AlterField(
            model_name='users',
            name='number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit phone number', regex='^[0-9]{10}$')]),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
