# Generated by Django 5.2.9 on 2026-03-26 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HubApp', '0019_alter_users_name_alter_users_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='Shipping',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
