# Generated by Django 5.2.9 on 2026-03-29 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HubApp', '0020_orders_shipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='users',
            name='number',
            field=models.IntegerField(),
        ),
    ]
